### ISSUE TITLE
新版本卡住ANR

### ISSUE THREAD

**Issue by Dean1990** [xuehuayous/Android-LoopView#4]
换了 1.3.1新版本后，自定义view，加载数据 setData  直接卡死，最后anr退出，然而并没有什么日志信息可以参考

**Comment by xuehuayous** [comment]
你好，使用方式可以说的详细点吗？

**Comment by Dean1990** [comment]
本来是在一个以前的工程里升级控件版本，从1.0.9  adloopview 改成bannerview ，出错后，就回归了，记得是改了以下几点：refreshData 到 setData , onClick 到 onItemClick , ItemData构造参数从5个到3个，getLoopData 改成getData,大概是这样，别的地方没有改动，然后运行了几次都是会卡死，没有日志信息，猜测可能是setData那里的问题，因为页面没有数据时，是正常的。

**Comment by xuehuayous** [comment]
多谢发现这个问题，的确是setData时UI操作引起的问题，我已经在1.4.0版本修复。
