### ISSUE TITLE
顺便提几个小问题

### ISSUE THREAD

**Issue by Dean1990** [xuehuayous/Android-LoopView#5]
别嫌我烦啊
1. declare-styleable  声明的是 `loop_layout` ，而 readme 里示例用的是 `loop_layoutId`;
2.自定义布局时 `loop_view_dots` 没有设置左边距，布局居中时容易看出来；
3.建议把  `xmlns:kevin="http://schemas.android.com/apk/res-auto" ` 这句注明，AS的alt+enter有时会提示补全 `xmlns:kevin="http://schemas.android.com/tools"` 导致设置无效，我一个不小心也掉坑里了...

**Comment by xuehuayous** [comment]
很高兴能反馈使用过程中遇到的问题，也是需要优化的地方。🤝
问题1和问题3在文档里修改了，问题2在1.4.1版本进行了修正。
