### ISSUE TITLE
内部Support包 版本不一致

### ISSUE THREAD

**Issue by chuwe1** [xuehuayous/Android-LoopView#6]
implementation "com.kevin:loopview:1.4.3"
这个东西里面有 23.3.0 的 support v4

跟其他的 appcompatv7 recyclerview cardView 之类的版本不一致 冲突了

**Comment by chuwe1** [comment]
https://github.com/xuehuayous/DelegationAdapter
里面有 依赖 本库的 两个冲突了

**Comment by xuehuayous** [comment]
请使用1.5.0版本，在改版本中support的依赖由implementation改为compileOnly。
