### ISSUE TITLE
关于图片切换速度问题

### ISSUE THREAD

**Issue by lsgmkk** [xuehuayous/Android-LoopView#7]
作者您好：我在代码中这样设置 bannerView.setScrollDuration(3000); 但是图片的切换速度没有变化，能解答一下吗？

**Comment by xuehuayous** [comment]
需要在`setData()`之后调用`setScrollDuration()`方法，如果这种方式不满足你的场景的话，我再修改下吧。

**Comment by lsgmkk** [comment]
嗯嗯，是这样的，我是在RecyclerView中使用多布局添加作为第一条数据的，第一次进来的时候会提示 mViewPager 为 null 所以反射修改 mScroller 就不成功，当我滑动 RecyclerView 直到bannerView消失在滑动回来的时候就可以了，页面的切换速度正常

**Comment by xuehuayous** [comment]
那我晚上修改下吧，添加一个属性配置，比如`loop_scrollDuration`，可以在XML中进行配置，然后代码中的也进行下优化。谢谢你的反馈。🤝

**Comment by lsgmkk** [comment]
哦哦，麻烦了。

**Comment by xuehuayous** [comment]
客气了，本来就是我的锅。

**Comment by xuehuayous** [comment]
在1.5.5版本添加了属性`loop_scrollDuration`，并且修复了`setScrollDuration()`的问题，推荐在XML中使用属性配置。

**Comment by lsgmkk** [comment]
好的，谢谢
